################################
## Airflow Worker Deployment
#################################
{{- $persistence := .Values.workers.persistence.enabled }}
{{- $additionalVolume := .Values.workers.additionalVolume }}
{{- if eq .Values.executor "CeleryExecutor" }}
kind: {{ if $persistence }}StatefulSet{{ else }}Deployment{{ end }}
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    tier: airflow
    component: worker
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $persistence }}
  serviceName: {{ .Release.Name }}-worker
{{- end }}
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      tier: airflow
      component: worker
      release: {{ .Release.Name }}
  {{- if and $persistence .Values.workers.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.workers.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if and (not $persistence) (.Values.workers.strategy) }}
  strategy:
    {{- toYaml .Values.workers.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        tier: airflow
        component: worker
        release: {{ .Release.Name }}
{{- with .Values.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
      annotations:
        checksum/metadata-secret: {{ include (print $.Template.BasePath "/secrets/metadata-connection-secret.yaml") . | sha256sum }}
        checksum/result-backend-secret: {{ include (print $.Template.BasePath "/secrets/result-backend-connection-secret.yaml") . | sha256sum }}
        checksum/pgbouncer-config-secret: {{ include (print $.Template.BasePath "/secrets/pgbouncer-config-secret.yaml") . | sha256sum }}
        checksum/airflow-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.workers.safeToEvict }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- end }}
        {{- if .Values.airflowPodAnnotations }}
        {{- toYaml .Values.airflowPodAnnotations | nindent 8 }}
        {{- end }}
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      terminationGracePeriodSeconds: {{ .Values.workers.terminationGracePeriodSeconds }}
      restartPolicy: Always
      serviceAccountName: {{ .Release.Name }}-worker-serviceaccount
      securityContext:
        runAsUser: {{ .Values.uid }}
        fsGroup: {{ .Values.gid }}
      {{- if or .Values.registry.secretName .Values.registry.connection }}
      imagePullSecrets:
        - name: {{ template "registry_secret" . }}
      {{- end }}
      initContainers:
      {{- if and $persistence .Values.workers.persistence.fixPermissions }}
        - name: volume-permissions
          image: {{ template "default_airflow_image" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          command:
            - chown
            - -R
            - "{{ .Values.uid }}:{{ .Values.gid }}"
            - {{ template "airflow_logs" . }}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: logs
              mountPath: {{ template "airflow_logs" . }}
      {{- end }}
        - name: wait-for-airflow-migrations
          image: {{ template "default_airflow_image" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          args: ["airflow-migration-spinner", "--timeout=60"]
          env:
          {{- include "standard_airflow_environment" . | indent 10 }}
{{- if .Values.workers.extraInitContainers }}
{{- toYaml .Values.workers.extraInitContainers | nindent 8 }}
{{- end }}
      containers:
        - name: worker
          image: {{ template "airflow_image" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          {{- if semverCompare ">=2.0.0" .Values.airflowVersion }}
          args: ["airflow", "celery", "worker"]
          {{- else }}
          args: ["airflow", "worker"]
          {{- end }}
          resources:
{{ toYaml .Values.workers.resources | indent 12 }}
          ports:
            - name: worker-logs
              containerPort: {{ .Values.ports.workerLogs }}
          volumeMounts:
{{- if $additionalVolume.enabled }}
            - name: worker-volume
              mountPath: {{ $additionalVolume.mountPath }}
{{- end }}
            - name: logs
              mountPath: {{ template "airflow_logs" . }}
            - name: config
              mountPath: {{ template "airflow_config_path" . }}
              subPath: airflow.cfg
              readOnly: true
            - name: config
              mountPath: {{ template "airflow_local_setting_path" . }}
              subPath: airflow_local_settings.py
              readOnly: true
{{- if .Values.workers.extraVolumeMounts }}
{{ toYaml .Values.workers.extraVolumeMounts | indent 12 }}
{{- end }}
          {{- include "airflow_environment_variables" . | indent 10 }}
{{- if $persistence }}
        - name: worker-gc
          image: {{ template "airflow_image" . }}
          args: ["/usr/local/bin/clean-airflow-logs"]
          volumeMounts:
            - name: logs
              mountPath: {{ template "airflow_logs" . }}
{{- end }}
{{- if .Values.workers.extraContainers }}
{{- toYaml .Values.workers.extraContainers | nindent 8 }}
{{- end }}
      volumes:
{{- if $additionalVolume.enabled }}
        - name: worker-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-worker-claim
{{- end }}
        - name: config
          configMap:
            name: {{ template "airflow_config" . }}
{{- if .Values.workers.extraVolumes }}
{{ toYaml .Values.workers.extraVolumes | indent 8 }}
{{- end }}
{{- if not $persistence }}
        - name: logs
          emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
      {{- if .Values.workers.persistence.storageClassName }}
        storageClassName: {{ .Values.workers.persistence.storageClassName }}
      {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.workers.persistence.size }}
{{- end }}
{{- end }}
